{% set name = "perl-uri" %}
{% set version = "5.32" %}
{% set sha256 = "9632067d34e14e0dae2da94631c4f25a387fcc48d06fa29330e8b3c04c4e913d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/URI-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-test-needs
    - perl-test-warnings
    - perl-test-fatal
  run:
    - perl
    - perl-business-isbn

test:
  imports:
    - URI

about:
  home: "https://github.com/libwww-perl/URI"
  summary: "Uniform Resource Identifiers (absolute and relative)."
  description: |
    This module implements the URI class. Objects of this class represent "Uniform Resource Identifier references" as specified in RFC 2396 (and updated by RFC 2732).
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  dev_url: "https://github.com/libwww-perl/URI"
  doc_url: "https://metacpan.org/pod/URI"

extra:
  recipe-maintainers:
    - fgiacomoni
    - conda-forge/perl-packagers
